[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm install",
  "cd ../frontend && npm install"
]

[phases.build]
cmds = [
  "cd ../frontend && npm run build",
  "cp -r ../frontend/dist ./public",
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "npx prisma db push && node dist/app.js"
